DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS adress;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS product;